<a href="https://colab.research.google.com/github/NirmaliePerera/FreeCodeCamp_DataAnalysisWithPython/blob/main/2_Pandas_Series_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# **Pandas Series exercises**

In [2]:
# Import the numpy package under the name np
import numpy as np

# Import the pandas package under the name pd
import pandas as pd

# Print the pandas version and the configuration
print(pd.__version__)

2.2.2

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## **Series creation**

### Create an empty pandas Series

In [3]:
pd.Series()

Series([], dtype: object)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y pandas Series

In [4]:
X = ['A','B','C']
print(X, type(X))

Y = pd.Series(X)
print(Y, type(Y)) # different type

['A', 'B', 'C'] <class 'list'>
0    A
1    B
2    C
dtype: object <class 'pandas.core.series.Series'>

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, name it 'My letters'

In [5]:
X = pd.Series(['A', 'B', 'C'])
X.name = 'My letters'
X

0    A
1    B
2    C
Name: My letters, dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its values

In [8]:
X = pd.Series(['JK', 'PK', 'SK'])
X.values

array(['JK', 'PK', 'SK'], dtype=object)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## **Series indexation**

### Assign index names to the given X pandas Series

In [10]:
X = pd.Series(['A', 'B', 'C'])
index_names = ['first', 'second', 'third']

X.index = index_names
X

first     A
second    B
third     C
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its first element

In [20]:
X = pd.Series(['Sunil','Amal','Piyal','Kamal'], index = ['first','second','third','fourth'])

#X[0] # by position
#X.iloc[0] # by position
X['first'] # by index

'Sunil'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its last element

In [21]:
X = pd.Series(['Sara','Lisa','Sneha'], index=['first', 'second', 'third'])

#X[-1] # by position
#X.iloc[-1] # by position
X['third'] # by index

'Sneha'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show all middle elements

In [22]:
X = pd.Series(['Apple','Ball','Cup','Dog','Elephant'],
              index=['A','B','C','D','E'])

#X[['B', 'C', 'D']]
#X.iloc[1:-1] # by position
X[1:-1] # by position

B    Ball
C     Cup
D     Dog
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the elements in reverse position

In [23]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X.iloc[::-1]
X[::-1]

fifth     E
forth     D
third     C
second    B
first     A
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the first and last elements

In [25]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['first', 'fifth']]
X.iloc[[0, -1]]
#X[[0, -1]]

first    A
fifth    E
dtype: object

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## **Series manipulation**

### Convert the given integer pandas Series to float

In [29]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

pd.Series(X, dtype=np.float64)

first     1.0
second    2.0
third     3.0
forth     4.0
fifth     5.0
dtype: float64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given pandas Series (first element becomes last)

In [30]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

X[::-1]

fifth     5
forth     4
third     3
second    2
first     1
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given pandas Series

In [33]:
X = pd.Series([40,25,51,12,73],
              index=['forth','second','fifth','first','third'])

X_sorted = X.sort_values()
X_sorted

first     12
second    25
forth     40
fifth     51
third     73
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, set the fifth element equal to 10

In [35]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])
X.iloc[4] = 10
X

first      1
second     2
third      3
forth      4
fifth     10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, change all the middle elements to 0

In [37]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X[1:-1] = 0
X

A    1
B    0
C    0
D    0
E    5
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, add 5 to every element

In [38]:
X = pd.Series([1,2,3,4,5],
              index=['A','B','C','D','E'])

X + 5

A     6
B     7
C     8
D     9
E    10
dtype: int64

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## **Series boolean arrays (also called masks)**

### Given the X pandas Series, make a mask showing negative elements

In [39]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

0     True
1    False
2     True
3     True
4    False
5    False
6     True
7     True
8     True
9    False
dtype: bool

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get the negative elements

In [40]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
X[mask]

0   -1
2    0
3   -4
6    0
7    0
8   -9
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than 5

In [41]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = X > 5
X[mask]

5     6
9    10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than the elements mean

In [47]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])


mask = X > X.mean()
X[mask]

1     2
4     5
5     6
9    10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers equal to 2 or 10

In [50]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

mask = (X == 2) | (X == 10)
X[mask]

1     2
9    10
dtype: int64

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## **Logic functions**

### Given the X pandas Series, return True if **none** of its elements is zero

In [55]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.all()

np.False_

In [54]:
X = pd.Series([-1,2,40,-4,5,6,60,20,-9,10])
X.all()

np.True_

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, return True if **any** of its elements is zero

In [56]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X.any()

np.True_

In [59]:
X = pd.Series([1,2,40,4,5,6,70,80,9,10])

X.any()

np.True_

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## **Summary statistics**

### Given the X pandas Series, show the sum of its elements

In [60]:
X = pd.Series([3,5,6,7,2,3,4,9,4])

#np.sum(X)
X.sum()

np.int64(43)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the mean value of its elements

In [61]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

#np.mean(X)
X.mean()

np.float64(3.7)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the max value of its elements

In [63]:
X = pd.Series([1,2,0,4,5,6,0,0,9,10])

np.max(X)
#X.max()

10